http:
  port: "8082"
  host: "0.0.0.0"

https:
  host: "0.0.0.0" 
  private.port: "8092"
  timeout: "120000"
  
semir:
  host: "scm.semir.com"
  getpath: "/thirdpartyapi/qc-wts/get-wts-data"
  updatepath: "/thirdpartyapi/qc-wts/update-qc-result-with-file-content"
  closepath: "/thirdpartyapi/qc-wts/close-wts"
  token: "![BRyka6gyqrnzx3kMm2aY2z7L6+3+2SycJTCZGNuTMzvnJ8SboBs4sy0Fn1Td/6Oo]"
  
ts:
  path: "semir-prod.jks"
  
api:
  id: "16528247"